### ISSUE TITLE
[BUG] Seed data missing administrator password for form-based authentication

### ISSUE THREAD

**Issue by metaturso** [rhythmictech/ansible-cortex#2]
## Describe the bug
The seed data loaded into ElasticSearch doesn't contain a password to authenticate to Cortex using the "initial username".

In my particular case I don't use LDAP or oAuth and I'd like a plain form login method.

## To Reproduce

Using the following host variables:

```yaml
cortex_load_seed_data: true
cortex_seed_initial_username: "admin"
cortex_api_key: SECRET_API_KEY
cortex_secret: MAYBE_A_PASSWORD
cortex_crypto_secret: MAYBE_A_PASSWORD
```

1. Provision a Cortex machine
2. Visit the Cortex GUI
3. Login using the user defined in `cortex_seed_initial_username`

## Expected behaviour
At this point I'd normally know what password to use, login and go on my merry way. However, this role currently defines **3 secrets** none of which is working.

One secret is the API key, one is defined but unused (see #1) and the last secret doesn't work for login (i.e. `cortex_crypto_secret`.

## Screenshots
![cortex](https://user-images.githubusercontent.com/30650/86236822-9d7c2680-bb92-11ea-8b66-16392e83331a.png)
